config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("notes.urls")),
    
]

notes/urls.py
from django.urls import path

from .views import index, note_details

app_name = "notes"

urlpatterns = [
    path("", index , name="index"),
    path("<str:secondary_id>/", note_details, name="note_details"),

]

notes/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User



class Note(models.Model):
    
    secondary_id = models.UUIDField(default=uuid.uuid4, unique=True)
    creator = models.ForeignKey(User, related_name="notes", on_delete=models.CASCADE, null=False, blank=False)
    title = models.CharField(max_length=2000, null=True, blank=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created"]
    
    def __str__(self):
        return str(self.id)
        

class NoteEditHistory(models.Model):

    secondary_id = models.UUIDField(default=uuid.uuid4, unique=True)
    edited_instance = models.ForeignKey(Note, related_name="previous_versions", on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=2000)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    

    class Meta:
        ordering = ["-created"]
    
    def __str__(self):
        return str(self.id)
        

notes/forms.py
from django import forms

from .models import Note


class NoteForm(forms.ModelForm):

    class Meta:
        model = Note
        fields = ["title", "body"]

        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Title'}),
            'body': forms.Textarea(
                attrs={'placeholder': 'Body'}),
        }

notes/views.py
import json
from django.shortcuts import render
from django.http import HttpResponse, HttpRequest
from django.core.paginator import Paginator

from .forms import NoteForm



def index(request: HttpRequest):
    if request.user.is_authenticated:
        if request.method == "POST":
            note_form = NoteForm(json.loads(request.body))

            if note_form.is_valid():
                note = note_form.save(commit=False)
                note.creator = request.user
                note.save()
                context = {
                    "note": note
                }
                return render(request, 'notes/partials/note.html', context, status=201)
            context = {
                "note_form": note_form
            }
            return render(request, 'notes/partials/note-form.html', context, status=400)

        else:
            note_form = NoteForm()
            notes = request.user.notes.all()

            paginator = Paginator(notes, 100)
            page_number = request.GET.get('page')
            page_obj = paginator.get_page(page_number)
            context = {
                "page_obj": page_obj,
                "note_form": note_form,
            }
            return render(request, "notes/index.html", context)
    else:
        return HttpResponse("Not Authenticated")



def note_details(request: HttpRequest, secondary_id:str):
    pass

notes/templates/notes/index.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block head %}

<style>
    body {
        background-color: #f4f3f3;
        padding: 16px;
    }
    .notes {
        margin: 0 auto;
    }
    .note {
        width: 100%;
        padding: 8px;
        box-sizing: border-box;
    }
    @media screen and (min-width: 560px) {
        .note {
            width: 33.33%;
        }
    }
    @media screen and (min-width: 816px) {
        .note {
            width: 25%;
        }
    }
    @media screen and (min-width: 1072px) {
        .note {
            width: 20%;
        }
    }
    .note-inner {
        background-color: #fff;
        min-height: 4em;
        border-radius: 10px;
        padding: 10px;
        box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 1px 5px 0 rgba(0, 0, 0, 0.12);
        transition: box-shadow 0.2s;
    }
    .note:hover .note-inner {
        box-shadow: 0 2px 15px rgba(0, 0, 0, 0.3);
    }
    
    a {
        color: inherit; 
        text-decoration: none; 
    }

    a:hover,
    a:active,
    a:visited {
        color: inherit; 
        text-decoration: none;
    }
    * {
        margin: 0;
        padding: 0;
    }
    .note-body {
        white-space: pre-wrap;
        word-wrap: break-word;
    }
    .form-container {
        border: 1px solid #ccc; 
        border-radius: 10px;
    }

    .form-container:focus-within {
        border: 2px solid #64c2ed;
        border-radius: 10px;
    }

    #id_title, #id_body {
        border: none; 
        width: 100%; 
        padding: 10px;
        box-sizing: border-box; 
        font-size: 16px;
    }

    #id_title:focus-within,  #id_body:focus-within {
        outline: none;
    }

    #id_body {
        resize: vertical; 
        height: 100px; 
    }

    .addNoteButton {
        margin-top: 8px;
        display: inline-block;
        outline: none;
        border-width: 0px;
        border-radius: 3px;
        box-sizing: border-box;
        font-size: inherit;
        font-weight: 500;
        max-width: 100%;
        text-align: center;
        text-decoration: none;
        transition: background 0.1s ease-out 0s, box-shadow 0.15s cubic-bezier(0.47, 0.03, 0.49, 1.38) 0s;
        background: rgb(0, 82, 204);
        cursor: pointer;
        height: 32px;
        line-height: 32px;
        padding: 0px 12px;
        vertical-align: middle;
        width: auto;
        font-size: 14px;
        color: rgb(255, 255, 255);
    }

    .addNoteButton:hover {
        background: rgb(0, 101, 255);
        text-decoration: inherit;
        transition-duration: 0s, 0.15s;
        color: rgb(255, 255, 255);
    }

    .centered-form {
        display: flex;
        justify-content: center; 
        text-align: center;
    }

    .centered-button {
        display: inline-block; 
    }
    
</style>
{% endblock head%}
{% block content %}
<main>
    <div class="centered-form">
        <form id="addNoteForm">
            {% include 'notes/partials/note-form.html' %}
            <button type="submit" class="addNoteButton centered-button">Add Note</button>
        </form>
    </div> 
    
    <div id="notes" class="notes">
        {% for note in page_obj %}
        {% include 'notes/partials/note.html' %}
        {% endfor %}
    </div>
    
</main>
{% endblock content %}

{% block script %}
<script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></script>
<script>

    function renderMasonry() {
        const iso = new Isotope('.notes');

        iso.layout({
            itemSelector: '.note',
            layoutMode: 'masonry'
        });
    }

    addEventListener("DOMContentLoaded", (event) => {
        renderMasonry();
    });



    const addNoteForm = document.querySelector("#addNoteForm");
    
    addNoteForm.addEventListener("submit", (event) => {
        event.preventDefault();
        const postData = Object.fromEntries(new FormData(event.target));
        const csrftoken= postData['csrfmiddlewaretoken'];

        
        fetch('/', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': csrftoken,
            },
            body: JSON.stringify(postData) 
        }).then(async (response)=> {
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }

            if (response.status === 201) {
                const data = await response.text();
                const notes = document.querySelector("#notes");
                notes.insertAdjacentHTML("afterbegin", data);
                renderMasonry();
            } else if (response.status === 400) {
                const data = response.text();
                console.log(data);
            } else {
                throw new Error('Network response was not ok');
            }
        }).catch(error => {
            
            console.error('There was a problem with the fetch operation:', error);
        });

    });

</script>
{% endblock script %}

notes/templates/notes/partials/note-form.html
{% csrf_token %}
<div class="form-container">
    <div>
        
        {{ note_form.title }}
        {% if note_form.title.errors %}
        <ul>
            {% for error in note_form.title.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div>
        {{ note_form.body }}
        {% if note_form.body.errors %}
        <ul>
            {% for error in note_form.body.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>

notes/templates/notes/partials/note.html
{% load humanize %}
<div class="note">
    <a href="{% url 'notes:note_details' note.secondary_id %}">
        <div class="note-inner">
            
            {% if note.title %}
            <h3>{{note.title}}</h3>
            {% endif %}
            <small>
                {{note.created|naturaltime}}
            </small>
            <p class="note-body">{{ note.body }}</p>
        </div>
    </a>
</div>

templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Notes</title>
    {% block head %}{% endblock head %}
  
</head>
<body>
    {% block content %}{% endblock %}
    {% block script %}{% endblock script %}
</body>
</html>